"""
30日年化波动率因子 - Custom Factor

计算股票最近30个交易日收盘价收益率的标准差，并年化为年化波动率（假设252个交易日），用于衡量价格波动风险
- 因子类型：technical（技术因子）
- 因子类别：volatility（波动率类）
- 回看周期：30（天数）
- 数据模型：ADSKLineModel（仅需行情数据中的`close`字段）

Generated by AI Factor Creator
Data Models: ADSKLineModel
"""

import numpy as np
from typing import Optional, List
from openfinance.datacenter.models.analytical import ADSKLineModel
from openfinance.quant.factors.base import (
    FactorBase,
    FactorMetadata,
    FactorType,
    FactorCategory,
)
from openfinance.quant.factors.registry import register_factor


@register_factor
class 30Volatility20260225115814Factor(FactorBase):
    """
    30日年化波动率因子
    
    计算股票最近30个交易日收盘价收益率的标准差，并年化为年化波动率（假设252个交易日），用于衡量价格波动风险
- 因子类型：technical（技术因子）
- 因子类别：volatility（波动率类）
- 回看周期：30（天数）
- 数据模型：ADSKLineModel（仅需行情数据中的`close`字段）
    """
    
    def _default_metadata(self) -> FactorMetadata:
        return FactorMetadata(
            factor_id="factor_30日年化volatility率因子_20260225115814",
            name="30日年化波动率因子",
            description="""计算股票最近30个交易日收盘价收益率的标准差，并年化为年化波动率（假设252个交易日），用于衡量价格波动风险
- 因子类型：technical（技术因子）
- 因子类别：volatility（波动率类）
- 回看周期：30（天数）
- 数据模型：ADSKLineModel（仅需行情数据中的`close`字段）""",
            factor_type=FactorType.CUSTOM,
            category=FactorCategory.VOLATILITY,
            lookback_period=30,
            required_fields=['close'],
            tags=['volatility', 'technical'],
            author="user",
        )
    
    def _calculate(self, klines: List[ADSKLineModel], **params) -> Optional[float]:
        '''Calculate factor value.'''
        30日年化波动率因子 - 计算最近N日收盘价收益率的年化标准差
        Args:
            klines: 行情数据列表，按trade_date升序排列（最旧数据在前，最新数据在后）
            period: 回看周期（默认30个交易日）
        Returns:
            float: 年化波动率（小数形式，如0.25表示25%），数据不足或异常时返回None
        Notes:
            - 使用对数收益率计算更符合金融惯例
            - 年化因子为sqrt(252)，对应A股年交易日数
            - 自动处理零值、空值和数据长度不足的情况
        if not klines or len(klines) < period + 1:
            return None
        close_prices = [k.close for k in klines if k.close is not None and k.close > 0]
        if len(close_prices) < period + 1:
            return None
        recent_prices = close_prices[-(period + 1):]
        try:
            returns = []
            for i in range(1, len(recent_prices)):
                if recent_prices[i-1] <= 0:
                    return None
                log_return = np.log(recent_prices[i] / recent_prices[i-1])
                returns.append(log_return)
            if len(returns) < period:
                return None
            volatility_daily = np.std(returns, ddof=1)
            volatility_annualized = volatility_daily * np.sqrt(252)
            if np.isnan(volatility_annualized) or np.isinf(volatility_annualized) or volatility_annualized < 0 or volatility_annualized > 5.0:
                return None
            return float(volatility_annualized)
        except (ZeroDivisionError, ValueError, OverflowError, TypeError):
            return None
