"""
chip_distribution_2y - Custom Factor

计算股票2年周期（约500个交易日）的筹码分布集中度，通过价格区间成交量加权分布的标准差倒数衡量筹码锁定程度；值越高表示筹码越集中在当前价格附近，主力控盘度越高
- 因子类型：technical
- 因子类别：liquidity
- 回看周期：500天

Generated by AI Factor Creator
"""

import numpy as np
from typing import Optional, List
from openfinance.datacenter.ads import ADSKLineModel
from openfinance.quant.factors.base import (
    FactorBase,
    FactorMetadata,
    FactorType,
    FactorCategory,
)
from openfinance.quant.factors.registry import register_factor


@register_factor
class ChipDistribution2y20260219135836Factor(FactorBase):
    """
    chip_distribution_2y
    
    计算股票2年周期（约500个交易日）的筹码分布集中度，通过价格区间成交量加权分布的标准差倒数衡量筹码锁定程度；值越高表示筹码越集中在当前价格附近，主力控盘度越高
- 因子类型：technical
- 因子类别：liquidity
- 回看周期：500天
    """
    
    def _default_metadata(self) -> FactorMetadata:
        return FactorMetadata(
            factor_id="factor_chip_distribution_2y_20260219135836",
            name="chip_distribution_2y",
            description="""计算股票2年周期（约500个交易日）的筹码分布集中度，通过价格区间成交量加权分布的标准差倒数衡量筹码锁定程度；值越高表示筹码越集中在当前价格附近，主力控盘度越高
- 因子类型：technical
- 因子类别：liquidity
- 回看周期：500天""",
            factor_type=FactorType.CUSTOM,
            category=FactorCategory.LIQUIDITY,
            lookback_period=500,
            required_fields=["close"],
            tags=['liquidity', 'technical'],
            author="user",
        )
    
    def _calculate(self, klines: List[ADSKLineModel], **params) -> Optional[float]:
        '''Calculate factor value.'''
        if not klines or len(klines) < self.metadata.lookback_period:
            return None
        
        close = np.array([k.close for k in klines])
        period = params.get("period", self.metadata.lookback_period)
        
        # Calculate momentum
        if len(close) < period:
            return None
        
        momentum = (close[-1] / close[-period]) - 1.0
        return float(momentum)
