template_id: research_report
name: Research Report Processing
description: Process research reports from EastMoney research center with entity extraction and sentiment analysis
version: 1.0.0
category: processing
tags:
  - research
  - report
  - nlp
  - eastmoney

stages:
  - id: fetch_reports
    name: Fetch Research Reports
    type: source
    handler: research_report_fetcher
    config:
      source: eastmoney
      include_pdf: true
      include_summary: true

  - id: parse_metadata
    name: Parse Report Metadata
    type: transform
    handler: metadata_parser
    config:
      extract_fields:
        - title
        - author
        - institution
        - publish_date
        - rating
        - target_price

  - id: parse_content
    name: Parse Report Content
    type: transform
    handler: content_parser
    config:
      extract_sections:
        - summary
        - analysis
        - conclusion
      max_content_length: 50000

  - id: extract_entities
    name: Extract Entities
    type: transform
    handler: entity_extractor
    config:
      entity_types:
        - company
        - industry
        - concept
        - person
      use_llm: true

  - id: extract_relations
    name: Extract Relations
    type: transform
    handler: relation_extractor
    config:
      relation_types:
        - recommends
        - affects
        - belongs_to
        - competes_with

  - id: analyze_sentiment
    name: Analyze Sentiment
    type: transform
    handler: sentiment_analyzer
    config:
      model: financial_sentiment
      include_confidence: true

  - id: validate_quality
    name: Validate Data Quality
    type: validate
    handler: data_validator
    config:
      check_required_fields: true
      min_confidence: 0.7

  - id: save_reports
    name: Save Reports
    type: sink
    handler: research_report_sink
    config:
      upsert: true
      store_content: true

  - id: update_graph
    name: Update Knowledge Graph
    type: sink
    handler: graph_updater
    config:
      create_entities: true
      create_relations: true
      link_to_stocks: true

edges:
  - source: fetch_reports
    target: parse_metadata
  - source: fetch_reports
    target: parse_content
  - source: parse_metadata
    target: extract_entities
  - source: parse_content
    target: extract_entities
  - source: parse_content
    target: analyze_sentiment
  - source: extract_entities
    target: extract_relations
  - source: extract_entities
    target: validate_quality
  - source: extract_relations
    target: validate_quality
  - source: analyze_sentiment
    target: validate_quality
  - source: validate_quality
    target: save_reports
  - source: save_reports
    target: update_graph

default_config:
  source: eastmoney
  days_back: 7
  max_reports: 100
  batch_size: 20
  timeout_seconds: 600

config_schema:
  type: object
  properties:
    source:
      type: string
      enum:
        - eastmoney
        - cninfo
    days_back:
      type: integer
      minimum: 1
      maximum: 365
    max_reports:
      type: integer
      minimum: 1
      maximum: 1000
