"""
Data Models Module for Data Center.

架构:
┌─────────────────────────────────────────────────────────────┐
│                    ADS Models (业务层)                        │
│         ADSModelRegistry + 统一业务模型                       │
├─────────────────────────────────────────────────────────────┤
│                    Repository Layer                          │
│         GenericADSRepository + 具体 Repository               │
├─────────────────────────────────────────────────────────────┤
│                    ORM Models                                │
│         SQLAlchemy 数据库模型                                 │
└─────────────────────────────────────────────────────────────┘
"""

from .mappings import (
    register_all_mappings,
    MAPPING_CONFIG,
)

from .orm import (
    Base,
    EntityModel,
    RelationModel,
    TaskChainModel,
    TaskExecutionModel,
    MonitoringMetricModel,
    AlertModel,
    ScheduledTaskModel,
    StockBasicModel,
    StockDailyQuoteModel,
    StockFinancialIndicatorModel,
    StockMoneyFlowModel,
    OptionQuoteModel,
    FutureQuoteModel,
    FactorDataModel,
    NewsModel,
    MacroEconomicModel,
    ESGRatingModel,
    EventModel,
    IncomeStatementModel,
    BalanceSheetModel,
    CashFlowModel,
    DividendDataModel,
    VALID_ENTITY_TYPES,
    VALID_RELATION_TYPES,
    ENTITY_TYPE_LABELS,
    RELATION_TYPE_LABELS,
)

from openfinance.datacenter.models.analytical import (
    ADSModel,
    ADSModelWithCode,
    ADSModelWithDate,
    ADSModelWithReportDate,
    ADSDataBatch,
    DataCategory,
    DataQuality,
    MarketType,
    ReportPeriod,
    ADSKLineModel,
    ADSMoneyFlowModel,
    ADSOptionQuoteModel,
    ADSFutureQuoteModel,
    ADSStockBasicModel,
    ADSFinancialIndicatorModel,
    ADSBalanceSheetModel,
    ADSIncomeStatementModel,
    ADSCashFlowModel,
    ADSShareholderModel,
    ADSShareholderChangeModel,
    ADSInsiderTradingModel,
    ADSMarketSentimentModel,
    ADSNewsModel,
    ADSStockSentimentModel,
    ADSMacroEconomicModel,
    ADSInterestRateModel,
    ADSExchangeRateModel,
    ADSFactorModel,
    ADSSignalModel,
    ADSBacktestResultModel,
    ADSMetaModel,
    ADSFieldMetaModel,
    ADSModelRegistry,
    ADSModelDefinition,
    register_ads_model,
    GenericADSRepository,
    ADSKLineRepository,
    ADSFactorRepository,
    get_model as get_ads_model,
)

__all__ = [
    "register_all_mappings",
    "MAPPING_CONFIG",
    "Base",
    "EntityModel",
    "RelationModel",
    "TaskChainModel",
    "TaskExecutionModel",
    "MonitoringMetricModel",
    "AlertModel",
    "ScheduledTaskModel",
    "StockBasicModel",
    "StockDailyQuoteModel",
    "StockFinancialIndicatorModel",
    "StockMoneyFlowModel",
    "OptionQuoteModel",
    "FutureQuoteModel",
    "FactorDataModel",
    "NewsModel",
    "MacroEconomicModel",
    "ESGRatingModel",
    "EventModel",
    "IncomeStatementModel",
    "BalanceSheetModel",
    "CashFlowModel",
    "DividendDataModel",
    "VALID_ENTITY_TYPES",
    "VALID_RELATION_TYPES",
    "ENTITY_TYPE_LABELS",
    "RELATION_TYPE_LABELS",
    "ADSModel",
    "ADSModelWithCode",
    "ADSModelWithDate",
    "ADSModelWithReportDate",
    "ADSDataBatch",
    "DataCategory",
    "DataQuality",
    "MarketType",
    "ReportPeriod",
    "ADSKLineModel",
    "ADSMoneyFlowModel",
    "ADSOptionQuoteModel",
    "ADSFutureQuoteModel",
    "ADSStockBasicModel",
    "ADSFinancialIndicatorModel",
    "ADSBalanceSheetModel",
    "ADSIncomeStatementModel",
    "ADSCashFlowModel",
    "ADSShareholderModel",
    "ADSShareholderChangeModel",
    "ADSInsiderTradingModel",
    "ADSMarketSentimentModel",
    "ADSNewsModel",
    "ADSStockSentimentModel",
    "ADSMacroEconomicModel",
    "ADSInterestRateModel",
    "ADSExchangeRateModel",
    "ADSFactorModel",
    "ADSSignalModel",
    "ADSBacktestResultModel",
    "ADSMetaModel",
    "ADSFieldMetaModel",
    "ADSModelRegistry",
    "ADSModelDefinition",
    "register_ads_model",
    "GenericADSRepository",
    "ADSKLineRepository",
    "ADSFactorRepository",
    "get_ads_model",
]
