"""
测试策略 - Custom Strategy

测试描述

Generated by AI Strategy Creator
"""

from typing import Optional
import pandas as pd
from openfinance.quant.strategy.base import (
    BaseStrategy,
    StrategyMetadata,
    StrategyType,
    WeightMethod,
    RebalanceFrequency,
)
from openfinance.quant.strategy.registry import register_strategy


@register_strategy
class TestFinalStrategy(BaseStrategy):
    """
    测试策略
    
    测试描述
    """
    
    def _default_metadata(self) -> StrategyMetadata:
        return StrategyMetadata(
            strategy_id="test_strategy_final",
            name="测试策略",
            description="""测试描述""",
            strategy_type=StrategyType.MULTI_FACTOR,
            factor_ids=['factor1', 'factor2'],
            tags=['test'],
        )
    
    def generate_signals(self, data: dict[str, pd.DataFrame], factor_values: Optional[dict] = None, date=None) -> dict[str, float]:
        '''Generate trading signals.'''
        signals = {}
        
        if not factor_values:
            return signals
        
        # Combine factor signals with weights
        factor_weights = {'factor1': 0.6, 'factor2': 0.4}
        
        for factor_id, scores in factor_values.items():
            weight = factor_weights.get(factor_id, 1.0 / len(factor_values))
            for code, score in scores.items():
                signals[code] = signals.get(code, 0) + weight * score
        
        return signals
    
    def calculate_portfolio_weights(self, signals: dict[str, float], prices: pd.DataFrame, covariance_matrix=None) -> dict[str, float]:
        '''Calculate portfolio weights.'''
        sorted_signals = sorted(signals.items(), key=lambda x: x[1], reverse=True)
        top_n = min(50, len(sorted_signals))
        
        weights = {}
        for code, _ in sorted_signals[:top_n]:
            weights[code] = 1.0 / top_n
        
        return weights
