"""
动量测试因子 - Custom Factor

测试用动量因子

Generated by AI Factor Creator
"""

import numpy as np
from typing import Optional, List
from openfinance.datacenter.ads import ADSKLineModel
from openfinance.quant.factors.base import (
    FactorBase,
    FactorMetadata,
    FactorType,
    FactorCategory,
    register_factor,
)


@register_factor
class MomentumTest001Factor(FactorBase):
    """
    动量测试因子
    
    测试用动量因子
    """
    
    def __init__(self):
        super().__init__()
        self._metadata = FactorMetadata(
            factor_id="factor_momentum_test_001",
            name="动量测试因子",
            description="""测试用动量因子""",
            factor_type=FactorType.TECHNICAL,
            category=FactorCategory.MOMENTUM,
            lookback_period=20,
            required_fields=["close"],
            tags=[],
            author="user",
        )
    
    @property
    def metadata(self) -> FactorMetadata:
        return self._metadata
    
    def calculate(self, klines: List[ADSKLineModel], **params) -> Optional[float]:
        '''
        Calculate factor value.
        
        Args:
            klines: List of ADSKLineModel objects, sorted by date ascending
            **params: Additional parameters
        
        Returns:
            float: Factor value, or None if insufficient data
        '''
        # Original generated code:
        # import numpy as np
        # def calculate_factor(klines, period=20):
        #     close = np.array([k.close for k in klines])
        #     return (close[-1] / close[-period] - 1) if len(close) >= period else None
        
        # Extracted calculation logic:
            close = np.array([k.close for k in klines])
            return (close[-1] / close[-period] - 1) if len(close) >= period else None
